# This is a YAML file
title: Website Name
description: A website for sharing content
github:
  event_name:push
tags:
 - technology
 - innovation
 - creativity
on: 
  push:
  
jobs: 
  first_job:
    runs-on : ubuntu-latest
    steps:
      - name : first_step
        run : echo "Hello guys"
      
      - name: ip_cheker
        run : ifconfig

