# This is a YAML file
name: Website Name
description: A website for sharing content

on: 
  push:
  
jobs: 
  first_job:
    runs-on : ubuntu-latest
    steps:
      - name : first_step
        run : echo "Hello guys"
      
      - name: ip_cheker
        run : ifconfig

