# This is a YAML file
name: Website Name
description: A website for sharing content

on: 
  push:
  
jobs: 
  first_job:
    runs-on : ubuntu-latest
    steps:
      - name : first_step
        run : echo "Hello guys"
      
      - name: ip_cheker
        run : ifconfig

      - uses : actions/checkout@v2

      - name : settig node version ${{matrix.node_version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name : installing dependency
        run : npm install

      - name : start
        run : npm run start



