# This is a YAML file
name: Website Name
description: A website for sharing content

on: 
  push:
  
jobs: 
  first_job:
    runs-on : ubuntu-latest
    steps:
      - name : first_step
        run : echo "Hello guys"

      - uses : actions/checkout@v2

      - name : setting node version ${{matrix.node_version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name : installing dependency
        run : npm install

      - name : testing
        run : npm run test
      
      - name : deplying
        run : echo "deploying"

      - name : deploy to ec2 instace
        uses : appleboy/ssh-action@v1.0.0
        with :
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key : ${{secrets.EC2_SSH_KEY}}
          script : |
            cd ${{secrets.EC2_APP_DIR}}
            git pull origin master
            npm install
            pm2 restart server.js



